---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-prod
  labels:
    ver: "1"
    app: "alpaca"
    env: "prod"
spec:
  replicas: 2
  selector:
    matchLabels: 
      ver: "1"
      app: "alpaca"
      env: "prod"
  template:
    metadata:
      labels:
        ver: "1"
        app: "alpaca"
        env: "prod"
    spec:
      containers:
      - name: alpaca-prod
        image: gcr.io/kuar-demo/kuard-amd64:blue
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-test
  labels:
    ver: "2"
    app: "alpaca"
    env: "test"
spec:
  replicas: 1
  selector:
    matchLabels: 
      ver: "2"
      app: "alpaca"
      env: "test"
  template:
    metadata:
      labels:
        ver: "2"
        app: "alpaca"
        env: "test"
    spec:
      containers:
      - name: alpaca-prod
        image: gcr.io/kuar-demo/kuard-amd64:green
        ports:
        - containerPort: 8080


